#!/usr/bin/env python3
"""Render a manuscript review: prepare context for LLM, then assemble final HTML.

Usage:
  python3 render_report.py prepare <review.json> <metacheck.json> <context_out.json>
  python3 render_report.py assemble <context.json> <body.html> <output.html>
"""

import html as html_mod
import json
import os
import re
import sys

# ---------------------------------------------------------------------------
# CSS loader
# ---------------------------------------------------------------------------

def load_css():
    css_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'report_style.css')
    with open(css_path, 'r', encoding='utf-8') as f:
        return f.read()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def esc(text):
    if text is None:
        return ""
    return html_mod.escape(str(text))


def md_bold(text):
    """Convert **bold** markers to <strong> tags. HTML-escapes first."""
    if text is None:
        return ""
    escaped = esc(text)
    return re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', escaped)


def grade_badge_css(grade):
    g = grade.strip().replace('\u2212', '-').replace('\u2013', '-').upper()
    mapping = {
        'A+': 'grade-a-plus', 'A': 'grade-a', 'A-': 'grade-a-minus',
        'B+': 'grade-b-plus-badge', 'B': 'grade-b-badge', 'B-': 'grade-b-badge',
        'C+': 'grade-c-badge', 'C': 'grade-c-badge', 'C-': 'grade-c-badge',
        'D+': 'grade-d-badge', 'D': 'grade-d-badge', 'D-': 'grade-d-badge',
        'F': 'grade-f-badge',
    }
    return mapping.get(g, 'grade-a')


def grade_card_css(grade):
    g = grade.strip().replace('\u2212', '-').replace('\u2013', '-').upper()
    if g.startswith('B'):
        return ' grade-b'
    if g.startswith('C'):
        return ' grade-c'
    if g.startswith('D'):
        return ' grade-d'
    if g == 'F':
        return ' grade-f'
    return ''


def grade_display(grade):
    g = grade.strip()
    return esc(g).replace('-', '&minus;')


def severity_badge(severity):
    s = severity.lower()
    return f'<span class="badge badge-{s}">{esc(severity.capitalize())}</span>'


def count_badges(issues):
    counts = {'critical': 0, 'major': 0, 'minor': 0}
    for issue in issues:
        s = issue.get('severity', '').lower()
        if s in counts:
            counts[s] += 1
    parts = []
    for sev in ('critical', 'major', 'minor'):
        if counts[sev] > 0:
            parts.append(
                f'<span class="count-badge count-{sev}">'
                f'{counts[sev]} {sev.capitalize()}</span>'
            )
    total = sum(counts.values())
    if total == 0:
        return '<span class="count-badge" style="background:#c6f6d5; color:#276749;">0 issues</span>'
    return f'{total} issue{"s" if total != 1 else ""}: {" ".join(parts)}'


def status_icon(status):
    s = status.lower()
    if s == 'pass':
        return '<span class="status-pass">&#10003;</span>'
    if s == 'fail':
        return '<span class="status-fail">&times;</span>'
    return '<span class="status-info">&#8505;</span>'


def issue_count_display(section):
    display = section.get('display_count')
    if display:
        if display.lower() in ('observations', 'skipped'):
            return f'<span class="issues-count" style="color: #a0aec0;">{esc(display)}</span>'
        return f'<span class="issues-count">{esc(display)}</span>'
    count = section.get('issue_count', 0)
    return f'<span class="issues-count">{count}</span>'


def metacheck_badge():
    return '<span class="badge-auto">[metacheck]</span>'


# ---------------------------------------------------------------------------
# Section renderers (for the HTML prefix)
# ---------------------------------------------------------------------------

def render_header(data):
    meta = data.get('metadata', {})
    title = esc(meta.get('manuscript_title', 'Untitled'))
    date = esc(meta.get('date', ''))
    return (
        f'<h1>MANUSCRIPT REVIEW REPORT</h1>\n'
        f'<p class="subtitle">{title}</p>\n'
        f'<p class="meta">{date} &bull; Review by Claude</p>'
    )


ABOUT_WITH_METACHECK = (
    'This report was generated by an AI-powered manuscript review skill for Claude Code. '
    'It combines LLM-based analysis with automated checks powered by the '
    '<a href="https://github.com/scienceverse/metacheck">metacheck R package</a> '
    '(DeBruine, 2024). Automated checks are marked with <span class="badge-auto">[metacheck]</span> badges. '
    'All suggestions should be verified by the authors. <strong>Note:</strong> Some apparent errors '
    'may stem from PDF text extraction and should be verified against the source document.'
)

ABOUT_WITHOUT_METACHECK = (
    'This report was generated by an AI-powered manuscript review skill for Claude Code. '
    'It checks for common formatting, referencing, and structural issues in academic manuscripts '
    'to help authors prepare their best work for submission. It also includes light content observations. '
    'Automated statistical and reference integrity checks were not performed in this review &mdash; '
    'install the <a href="https://github.com/scienceverse/metacheck">metacheck R package</a> '
    'for retraction screening, PubPeer lookups, and statistical error detection. '
    'All suggestions should be verified by the authors. <strong>Note:</strong> Some apparent errors '
    'may stem from PDF text extraction and should be verified against the source document.'
)


def render_about(data):
    mc = data.get('metadata', {}).get('metacheck_available', False)
    text = ABOUT_WITH_METACHECK if mc else ABOUT_WITHOUT_METACHECK
    return (
        f'<div class="about-box">\n'
        f'  <h2>ABOUT THIS REPORT</h2>\n'
        f'  <p>{text}</p>\n'
        f'</div>'
    )


def render_summary(data):
    summary = data.get('overall_summary', {})
    text = esc(summary.get('text', ''))
    c = summary.get('critical_count', 0)
    m = summary.get('major_count', 0)
    mi = summary.get('minor_count', 0)
    parts = [
        '<h2 class="section-title">OVERALL SUMMARY</h2>',
        '<hr class="section-divider">',
        f'<p class="summary-text">{text}</p>',
        '<div class="stats-row">',
        '  <div class="stat-box">',
        '    <div class="stat-label">CRITICAL ISSUES</div>',
        f'    <div class="stat-number critical">{c}</div>',
        '  </div>',
        '  <div class="stat-box">',
        '    <div class="stat-label">MAJOR ISSUES</div>',
        f'    <div class="stat-number major">{m}</div>',
        '  </div>',
        '  <div class="stat-box">',
        '    <div class="stat-label">MINOR ISSUES</div>',
        f'    <div class="stat-number minor">{mi}</div>',
        '  </div>',
        '</div>',
    ]

    # Critical issues inline
    for issue in data.get('top_critical_issues') or []:
        parts.append(
            f'<div class="issue-card">\n'
            f'  <strong>{esc(issue.get("title", ""))}</strong> &mdash; {esc(issue.get("category", ""))}<br>\n'
            f'  <span style="font-size: 14px; color: #4a5568;">{esc(issue.get("details", ""))}</span>\n'
            f'</div>'
        )

    return '\n'.join(parts)


def render_language_quality(data):
    lq = data.get('language_quality', {})
    overall = lq.get('overall_grade', 'N/A')
    badge_css = grade_badge_css(overall)

    parts = [
        '<h2 class="section-title">LANGUAGE QUALITY</h2>',
        '<hr class="section-divider">',
        f'<p class="summary-text">\n'
        f'  Overall language quality: <span class="overall-grade {badge_css}">{grade_display(overall)}</span>\n'
        f'</p>',
    ]

    dims = lq.get('dimensions') or []
    for dim in dims:
        grade = dim.get('grade', 'N/A')
        card_extra = grade_card_css(grade)
        parts.append(
            f'<div class="grade-card{card_extra}">\n'
            f'  <div>\n'
            f'    <div class="grade-title">{esc(dim.get("name", ""))}</div>\n'
            f'    <div class="grade-desc">{esc(dim.get("description", ""))}</div>\n'
            f'  </div>\n'
            f'  <div class="grade-badge {grade_badge_css(grade)}">{grade_display(grade)}</div>\n'
            f'</div>'
        )

    strengths = lq.get('key_strengths') or []
    if strengths:
        parts.append('<strong class="label">Key Strengths</strong>')
        parts.append('<ul class="strengths-list">')
        for s in strengths:
            parts.append(f'  <li>{esc(s)}</li>')
        parts.append('</ul>')

    improvements = lq.get('areas_for_improvement') or []
    if improvements:
        parts.append('<strong class="label">Areas for Improvement</strong>')
        parts.append('<ul class="improvements-list">')
        for i in improvements:
            parts.append(f'  <li>{esc(i)}</li>')
        parts.append('</ul>')

    return '\n'.join(parts)


def render_section_review_table(data):
    categories = data.get('check_categories') or []
    sections = data.get('section_review') or []

    # If no explicit section_review, derive from check_categories
    if not sections:
        section_descs = {
            1: "Clarity, length, accuracy",
            2: "Hierarchy, consistency, formatting",
            3: "Author details, affiliations, compliance statements",
            4: "Structure, completeness, length",
            5: "Overall organization, section order",
            6: "Captions, cross-references, formatting",
            7: "APA format, DOIs, retraction checks",
            8: "Grammar, spelling, style",
            9: "Definition on first use, consistency",
            10: "Ethics, COI, data availability, open science",
            11: "Causal language, limitations, sample description",
            12: "APA format, statcheck, p-values",
        }
        for cat in categories:
            n = cat.get('number', 0)
            issues = cat.get('issues') or []
            obs = cat.get('content_observations') or []
            sub_issues = []
            for sub in (cat.get('subsections') or []):
                sub_issues.extend(sub.get('issues') or [])
            total = len(issues) + len(sub_issues)

            # Determine status
            if total > 0:
                st = 'fail'
            elif cat.get('metacheck_info') or cat.get('subsections'):
                st = 'info'
            else:
                st = 'pass'

            sections.append({
                'name': f"{n}. {cat.get('name', '')}",
                'description': section_descs.get(n, ''),
                'status': st,
                'issue_count': total,
                'display_count': str(total) if total > 0 else ('Observations' if obs and total == 0 and n == 11 else str(total)),
            })

    rows = []
    for sec in sections:
        rows.append(
            f'    <tr>\n'
            f'      <td>\n'
            f'        <div class="table-section-name">{esc(sec.get("name", ""))}</div>\n'
            f'        <div class="table-section-desc">{esc(sec.get("description", ""))}</div>\n'
            f'      </td>\n'
            f'      <td>{status_icon(sec.get("status", "pass"))}</td>\n'
            f'      <td>{issue_count_display(sec)}</td>\n'
            f'    </tr>'
        )
    return (
        '<h2 class="section-title">SECTION REVIEW</h2>\n'
        '<hr class="section-divider">\n\n'
        '<table class="review-table">\n'
        '  <thead>\n'
        '    <tr><th>SECTION</th><th>STATUS</th><th>ISSUES</th></tr>\n'
        '  </thead>\n'
        '  <tbody>\n'
        + '\n'.join(rows) + '\n'
        '  </tbody>\n'
        '</table>'
    )


# ---------------------------------------------------------------------------
# Metacheck snippet generators
# ---------------------------------------------------------------------------

def render_doi_table(suggestions):
    if not suggestions:
        return ''
    confidence_icons = {
        'high': '<span class="status-pass">&#10003;</span>',
        'moderate': '<span class="status-info">&#8505;</span>',
        'low': '<span class="status-fail">&times;</span>',
    }
    rows = []
    for s in suggestions:
        ref = esc(s.get('reference', ''))
        doi = s.get('doi', '')
        doi_url = s.get('doi_url', f'https://doi.org/{doi}')
        conf = s.get('confidence', 'moderate').lower()
        icon = confidence_icons.get(conf, confidence_icons['moderate'])
        rows.append(
            f'    <tr>\n'
            f'      <td>{ref}</td>\n'
            f'      <td style="text-align: left;"><a href="{esc(doi_url)}">{esc(doi)}</a></td>\n'
            f'      <td>{icon}</td>\n'
            f'    </tr>'
        )
    return (
        '<table class="review-table" style="font-size: 13px;">\n'
        '  <thead>\n'
        '    <tr><th>REFERENCE</th><th style="text-align: left;">SUGGESTED DOI</th><th>CONFIDENCE</th></tr>\n'
        '  </thead>\n'
        '  <tbody>\n'
        + '\n'.join(rows) + '\n'
        '  </tbody>\n'
        '</table>\n'
        '<p style="font-size: 12px; color: #718096;">Confidence based on CrossRef match scores from metacheck.</p>'
    )


def render_statcheck_table(results):
    if not results:
        return ''
    rows = []
    for r in results:
        st = r.get('status', 'pass').lower()
        icon = '<span class="status-pass">&#10003;</span>' if st == 'pass' else '<span class="status-fail">&times;</span>'
        rows.append(
            f'    <tr>\n'
            f'      <td style="font-size: 13px;">{esc(r.get("reported", ""))}</td>\n'
            f'      <td style="font-size: 13px;">{esc(r.get("computed", ""))}</td>\n'
            f'      <td>{icon}</td>\n'
            f'    </tr>'
        )
    return (
        '<table class="review-table" style="margin-top: 12px;">\n'
        '  <thead>\n'
        '    <tr><th>TEST</th><th>REPORTED</th><th>STATUS</th></tr>\n'
        '  </thead>\n'
        '  <tbody>\n'
        + '\n'.join(rows) + '\n'
        '  </tbody>\n'
        '</table>'
    )


def render_replication_results(results):
    if not results:
        return ''
    parts = []
    for r in results:
        orig = esc(r.get('original', ''))
        repl = esc(r.get('replication', ''))
        context = r.get('context_note', '')
        parts.append('<div class="issue-card no-break">')
        parts.append(f'  <p><strong>Original:</strong> {orig}</p>')
        parts.append(f'  <p><strong>Replication:</strong> {repl}</p>')
        if context:
            parts.append(f'  <p style="font-size: 13px; color: #718096; margin-top: 8px;">{md_bold(context)}</p>')
        parts.append('</div>')
    return '\n'.join(parts)


def clean_metacheck_report(report):
    """Extract clean summary text from a metacheck report field (may be list or string)."""
    if isinstance(report, list):
        parts = []
        for item in report:
            text = str(item).strip()
            # Skip entire items that are code blocks
            if '```{r}' in text or text.startswith('```') or 'structure(list(' in text:
                continue
            # Take first meaningful line
            for line in text.split('\n'):
                line = line.strip()
                if line and not line.startswith('```') and not line.startswith('#|') and not line.startswith('# ') and not line.startswith('>'):
                    parts.append(line.rstrip(':').rstrip())
                    break
        return '; '.join(parts) if parts else ''
    return str(report).strip()


# ---------------------------------------------------------------------------
# Metacheck injection
# ---------------------------------------------------------------------------

def inject_metacheck(data, metacheck):
    """Inject metacheck data into check_categories and return pre-generated snippets."""
    # Only structured tables are pre-rendered as HTML snippets.
    # Narrative content (retraction, open science, p-values, marginal notes)
    # stays in metacheck_info for the LLM to write proper narratives.
    snippets = {
        'doi_table': '',
        'statcheck_table': '',
        'replication_results': '',
    }

    if not metacheck or 'results' not in metacheck:
        return snippets

    results = metacheck['results']
    cats = {c['number']: c for c in data.get('check_categories') or []}

    # --- Category 7: Referencing ---
    cat7 = cats.get(7)
    if cat7:
        mc = cat7.setdefault('metacheck_info', {}) or {}
        cat7['metacheck_info'] = mc

        # DOI suggestions with filtering
        doi_exclusions = set(mc.get('doi_exclusions') or [])
        doi_check = results.get('ref_doi_check', {}).get('table') or []
        doi_suggestions = []
        for entry in doi_check:
            doi = entry.get('DOI')
            ref_raw = entry.get('ref', '')

            # Filter GROBID artifacts
            if '(????)' in ref_raw:
                continue
            # Filter entries without a parenthesised year
            if not re.search(r'\(\d{4}\)', ref_raw):
                continue
            if not doi or doi in doi_exclusions:
                continue

            score = entry.get('score', 0)
            if score >= 60:
                conf = 'high' if score > 100 else 'moderate'
            else:
                conf = 'low'

            # Clean reference text: strip all HTML tags and decode entities
            ref_text = re.sub(r'<[^>]+>', '', ref_raw)
            ref_text = html_mod.unescape(ref_text)

            doi_suggestions.append({
                'reference': ref_text,
                'doi': doi,
                'doi_url': f'https://doi.org/{doi}',
                'confidence': conf,
            })

        if doi_suggestions:
            mc['doi_suggestions'] = doi_suggestions
            snippets['doi_table'] = render_doi_table(doi_suggestions)

        # Retraction summary — clean text for the LLM to narrate
        retraction = results.get('ref_retraction', {})
        pubpeer = results.get('ref_pubpeer', {})
        ret_text = clean_metacheck_report(retraction.get('report', ''))
        pubpeer_text = clean_metacheck_report(pubpeer.get('report', ''))
        # Deduplicate shared prefix like "We checked N references with DOIs."
        if ret_text and pubpeer_text:
            # Find first sentence of each
            ret_first = ret_text.split('. ')[0] + '.'
            pub_first = pubpeer_text.split('. ')[0] + '.'
            if ret_first == pub_first:
                # Strip shared prefix from pubpeer
                pubpeer_text = pubpeer_text[len(pub_first):].strip()
            summary = f"{ret_text} {pubpeer_text}".strip()
        else:
            summary = ret_text or pubpeer_text
        if summary and not mc.get('retraction_summary'):
            mc['retraction_summary'] = summary

        # Replication results
        repl = results.get('ref_replication', {}).get('table') or []
        if repl:
            repl_results = []
            for r in repl:
                repl_results.append({
                    'original': r.get('original_ref', r.get('ref', '')),
                    'replication': r.get('replication_ref', r.get('flora_ref', '')),
                    'context_note': r.get('context', None),
                })
            if not mc.get('replication_results'):
                mc['replication_results'] = repl_results
            snippets['replication_results'] = render_replication_results(repl_results)

    # --- Category 12: Statistical Reporting ---
    cat12 = cats.get(12)
    if cat12:
        mc = cat12.setdefault('metacheck_info', {}) or {}
        cat12['metacheck_info'] = mc

        # Statcheck results
        stat_check = results.get('stat_check', {}).get('table') or []
        if stat_check:
            sc_results = [
                {
                    'reported': s.get('raw', ''),
                    'computed': f"Computed p = {s.get('computed_p', 'N/A')}",
                    'status': 'fail' if s.get('error') else 'pass',
                }
                for s in stat_check
            ]
            if not mc.get('statcheck_results'):
                mc['statcheck_results'] = sc_results
            snippets['statcheck_table'] = render_statcheck_table(sc_results)

        # P-value summary — stored in metacheck_info for LLM to narrate
        p_vals = results.get('all_p_values', {}).get('table') or []
        if p_vals and not mc.get('p_value_summary'):
            mc['p_value_summary'] = f"{len(p_vals)} p-values detected in the manuscript."

        # Marginal significance — stored in metacheck_info for LLM to narrate
        marginal = results.get('marginal', {}).get('table') or []
        if marginal and not mc.get('marginal_notes'):
            mc['marginal_notes'] = f"{len(marginal)} instance(s) of marginal significance language found."

    # --- Category 10: Funding & Compliance ---
    cat10 = cats.get(10)
    if cat10:
        mc = cat10.setdefault('metacheck_info', {}) or {}
        cat10['metacheck_info'] = mc

        open_sci = []
        op = results.get('open_practices', {})
        if op.get('report'):
            open_sci.append(f"Open practices: {clean_metacheck_report(op['report'])}")
        prereg = results.get('prereg_check', {})
        if prereg.get('report'):
            open_sci.append(f"Preregistration: {clean_metacheck_report(prereg['report'])}")
        coi = results.get('coi_check', {})
        if coi.get('report'):
            open_sci.append(f"COI statement: {clean_metacheck_report(coi['report'])}")
        funding = results.get('funding_check', {})
        if funding.get('report'):
            open_sci.append(f"Funding statement: {clean_metacheck_report(funding['report'])}")
        if open_sci and not mc.get('open_science'):
            mc['open_science'] = open_sci

    return snippets


# ---------------------------------------------------------------------------
# prepare: Generate render context for LLM
# ---------------------------------------------------------------------------

def prepare(review_path, metacheck_path, output_path):
    with open(review_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    metacheck = None
    if metacheck_path:
        try:
            with open(metacheck_path, 'r', encoding='utf-8') as f:
                metacheck = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError) as e:
            print(f"Warning: Could not load metacheck data: {e}", file=sys.stderr)

    # Inject metacheck and get pre-generated snippets
    snippets = inject_metacheck(data, metacheck)

    # Build HTML prefix (everything up through section review table)
    css = load_css()
    prefix_parts = [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '<title>Manuscript Review Report</title>',
        f'<style>\n{css}</style>',
        '</head>',
        '<body>',
        '',
        render_header(data),
        '',
        render_about(data),
        '',
        render_summary(data),
        '',
        render_language_quality(data),
        '',
        render_section_review_table(data),
        '',
    ]

    # Generate count badges for each category
    category_badges = {}
    for cat in data.get('check_categories') or []:
        n = cat.get('number', 0)
        all_issues = (cat.get('issues') or [])
        for sub in (cat.get('subsections') or []):
            all_issues = all_issues + (sub.get('issues') or [])
        category_badges[str(n)] = count_badges(all_issues)

    context = {
        'html_prefix': '\n'.join(prefix_parts),
        'html_suffix': '\n</body>\n</html>',
        'snippets': snippets,
        'category_badges': category_badges,
        'check_categories': data.get('check_categories') or [],
    }

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(context, f, ensure_ascii=False, indent=2)

    print(f"Render context written to {output_path}", file=sys.stderr)


# ---------------------------------------------------------------------------
# assemble: Combine prefix + LLM body + suffix
# ---------------------------------------------------------------------------

def postprocess_body(body):
    """Fix common LLM output issues in the body HTML."""
    # Convert **bold** markers to <strong> tags (LLMs sometimes leave these unconverted)
    body = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', body)
    return body


def assemble(context_path, body_path, output_path):
    with open(context_path, 'r', encoding='utf-8') as f:
        context = json.load(f)

    with open(body_path, 'r', encoding='utf-8') as f:
        body = f.read()

    body = postprocess_body(body)
    html_content = context['html_prefix'] + '\n' + body + '\n' + context['html_suffix']

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)

    print(f"Report written to {output_path}", file=sys.stderr)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print("Usage:", file=sys.stderr)
        print("  render_report.py prepare <review.json> <metacheck.json> <context_out.json>", file=sys.stderr)
        print("  render_report.py assemble <context.json> <body.html> <output.html>", file=sys.stderr)
        sys.exit(1)

    command = sys.argv[1]

    if command == 'prepare':
        if len(sys.argv) < 5:
            print("Usage: render_report.py prepare <review.json> <metacheck.json> <context_out.json>", file=sys.stderr)
            sys.exit(1)
        prepare(sys.argv[2], sys.argv[3], sys.argv[4])

    elif command == 'assemble':
        if len(sys.argv) < 5:
            print("Usage: render_report.py assemble <context.json> <body.html> <output.html>", file=sys.stderr)
            sys.exit(1)
        assemble(sys.argv[2], sys.argv[3], sys.argv[4])

    else:
        print(f"Unknown command: {command}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
